import type { Metadata } from "next";
import { Antonio, League_Spartan } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";

const antonio = Antonio({
  subsets: ["latin"],
  variable: "--font-antonio",
});

const spartan = League_Spartan({
  subsets: ["latin"],
  variable: "--font-spartan",
});

export const metadata: Metadata = {
  title: "Frontend Mentor | Planets fact site",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${antonio.variable} ${spartan.variable} h-screen bg-dark-navy bg-stars text-white antialiased`}
      >
        <Header />
        <main className="relative h-[calc(100%_-_69px)]">{children}</main>
      </body>
    </html>
  );
}
